### PR TITLE
Fix HAPROXY_SSL_OPTS typo

### PR DESCRIPTION
**Pull request by tmrudick**
Example SNI command was incorrectly using HAPROXY_SSL_OPTIONS. The correct environment variable name is HAPROXY_SSL_OPTS.

### CODE REVIEW

**Comment by ehazlett** [comment]
Hey thanks!  Would you mind checking out the `ng` branch?  I'm getting ready to merge that and I don't want to smash this commit.  Sorry and thanks!

**Comment by tmrudick** [comment]
No problem! Looks like this set of docs is no longer around in the ng branch.

**Comment by ehazlett** [comment]
Ya sorry the new docs are here (I revamped them because they were out of
date and no longer accurate):
https://github.com/ehazlett/interlock/tree/ng/docs

**Comment by tmrudick** [comment]
Just getting back to this. The typo doesn't exist in the new docs so I am just going to close this PR instead of rebasing.

**Comment by ehazlett** [comment]
Sounds good thx!!

**Pull request closed without merging**
