### PR TITLE
Feature request: To achive session-stickiness in HA Proxy

### PR DESCRIPTION
**Pull request by ManMohanVyas**
Please check it once. I have added session stickiness support.
It can be done via **-sticky true** 

Kindly let me know if there is any issue in approach. 

Thanks for consideration

### CODE REVIEW

**Comment by ManMohanVyas** [comment]
@ehazlett  Sir, Is anything wrong with the pull request?? Kindly let me know if it needs to enhanced.

**Comment by ehazlett** [comment]
Thanks for the contribution!  I think would be better on the INTERLOCK_DATA so you could configure each backend instead of globally. Swarm support is coming too along with auto-reconnect and tcp support soon. That changes how the data is handled. I can actually add this support in that branch pretty quick if you want me to do it there. The branches are swarm and tcp-support if you are interested. 

Thanks!

**Comment by ManMohanVyas** [comment]
@ehazlett  Thank you, But allow me to this small change. Will send you pull request again.
But are you removing the shipyard support. We were using shipyard+interlock+docker for the scaling?

**Comment by ehazlett** [comment]
I like the idea of being able to set stickyness but not global.  We need to move it to the INTERLOCK_DATA.

Shipyard is also moving to Swarm as far as the backend so they will work nicely together.  The interlock image will be versioned to not break current deployments.  Shipyard should also work nicely as the current backend is very similar to Swarm.  There will most likely be more integration

**Comment by ehazlett** [comment]
Closing as there has been a large refactor (`ng` branch).  Please re-open a new PR against that.  Thanks!

**Pull request closed without merging**
