### PR TITLE
Externalize templates but default to internal templates

### PR DESCRIPTION
**Pull request by everett-toews**

### CODE REVIEW

**Comment by ehazlett** [comment]
sweet thanks!  i'll get this checked!

**Comment by lukad** [comment]
This feature is really useful for me. Is there anything I can do to help get it merged?

**Comment by everett-toews** [comment]
@ehazlett Is there anything else I can do to help get this merged?

**Comment by ehazlett** [comment]
Sorry for the delay!  I'll get this tested tonight.

**Comment by ehazlett** [comment]
Hmm for some reason I'm having an issue with this updating the proxy config.  This build wasn't finding the proxy containers.  We might want to check that algorithm again.

**Comment by ehazlett** [comment]
Actually this looks like it might be a problem in master.  I'm taking a look.

**Comment by ehazlett** [comment]
I fixed the issue in master.  lgtm -- thanks!!

**Pull request merged**
