### PR TITLE
Add support for IP hash sticky sessions

### PR DESCRIPTION
**Pull request by krishamoud**
Previously it was not possible to connect to a meteor server with websockets enabled and the connection would always fall back to `sockjs`. Also, `ip_hash` sticky sessions weren't possible.

If the label `"interlock.meteor_application=true"` is added both `ip_hash` sticky sessions and websocket connections are enabled.  

This nginx configuration is based off the documentation I found here: 
http://www.meteorpedia.com/read/nginx

### CODE REVIEW

**Comment by everett-toews** [comment]
@krishamoud It's likely these changes won't be necessary after https://github.com/ehazlett/interlock/pull/104 merges. That PR gives you full control over the Nginx template so you don't need to change any Go code to add support for stuff like this.

Do you think https://github.com/ehazlett/interlock/pull/104 will work for your use case?

**Comment by krishamoud** [comment]
It looks promising!

Until that PR gets merged I'll just keep a forked image using the code that I've already written.

**Comment by ehazlett** [comment]
@krishamoud thanks!  why are you not using the existing WebsocketEndpoints?  We can add the ip hash as well but should be an option.  I'm trying to stay generic with the options and not configure for a specific application or framework.  I think we could have a minor update to the WebsocketEndpoints and get what you need.

@everett-toews While #104 looks good we shouldn't rely on it for everything.  Part of the benefit of Interlock is a sane default load balancer configuration without writing Nginx/HAProxy templates.

**Comment by krishamoud** [comment]
I tried to use the websockets endpoint first but was unable to get it to work for what I needed. This was a first pass attempt to see what your thoughts were.

I completely agree that interlock should stay as generic as possible. I will do some work today to see if I can get it to my personal use cases while still maintaining a generic template that doesn't cater to any framework in particular.

**Comment by krishamoud** [comment]
Ok, really quick update.  I was able to get the websocket endpoint to work without editing the conf file.  I was being dumb and used the wrong endpoint which was causing a lot of other problems.  When I used the correct endpoint I was able to use the current websocket implementation perfectly fine.  I will update my code to only include the `ip_hash` and nothing more.

**Comment by ehazlett** [comment]
:+1: 

would you also mind rebasing and squashing the commits?  thx!

**Comment by krishamoud** [comment]
Yep.  Sorry I screwed something up the first time I tried rebasing and it ended up taking longer than I wanted it to.

**Comment by ehazlett** [comment]
carried in #129.  thanks!!

**Pull request closed without merging**
