### PR TITLE
Proxy protocol support

### PR DESCRIPTION
**Pull request by vixns**
haproxy only
add new label interlock.protocol=proxy as proposed in #96

### CODE REVIEW

**Comment by vixns** [comment]
rebased

**Comment by ehazlett** [comment]
sorry this is not rebased.  i can't merge this as it will cause a bunch of conflicts and potential merge overwrites.

**Comment by vixns** [comment]
fixed

**Comment by ehazlett** [comment]
Here is some info on rebasing: https://docs.docker.com/opensource/FAQ/#how-do-i-rebase-my-feature-branch.  You will need to squash your commits and then rebase.  I'm going to close this for now but feel free to open a new PR based off of the latest master and ping if you need help!  Thanks!

**Pull request closed without merging**
