### PR TITLE
Externalize the extension configuration templates

### LINKED ISSUE #91: Externalize the extension configuration templates
## Feature Request

Currently the extension configuration templates like [nginx/template.go](https://github.com/ehazlett/interlock/blob/master/ext/nginx/template.go) and [haproxy/template.go](https://github.com/ehazlett/interlock/blob/master/ext/haproxy/template.go) are compiled right into Interlock. That means you're locked into the how that configuration is done.

The extension configuration templates should be externalized as simple text files that can make use of Interlock variables (e.g. `{{ $host.Name }}`). You could then include the configuration templates in your `Dockerfile` to be consumed by Interlock.

### PR DESCRIPTION
**Pull request by everett-toews**
Building on the [overlay-support](https://github.com/ehazlett/interlock/tree/overlay-support) branch.

There's a lot of work left to do on this but I wanted to get this out early with just one template done to work out the design issues.

 - [x] default extension template path as per https://github.com/ehazlett/interlock/blob/overlay-support/config/utils.go#L8
 - [x] externalize all templates
 - [x] docs

I'm testing by building a Swarm with [swarmer](https://github.com/everett-toews/swarmer) and this

```
docker run -it \
  --name dev \
  --net mynetwork \
  --publish 8080:8080 \
  --volume $(pwd)/config.toml:/bin/config.toml \
  --volume $(pwd)/docs/examples/nginx/nginx.conf.template:/etc/interlock/nginx.conf.template \
  --volume $DOCKER_CERT_PATH:/etc/docker/ \
  --volume `pwd`:/go/src/github.com/ehazlett/interlock \
  golang:1.6-wheezy \
  /bin/bash

cd src/github.com/ehazlett/interlock/
make build
cmd/interlock/interlock -D run
```

Closes #91

### CODE REVIEW

**Comment by ehazlett** [comment]
Ya overall this looks like a good direction.  We will have to be careful about error handling as this could blow up more easily as it will be user provided.  Perhaps we should attempt to compile the template early to make sure as a first step.

**Comment by everett-toews** [comment]
If the user forgets to include a template, it will fails pretty fast in ~1 sec. 

```
# time cmd/interlock/interlock -D run
INFO[0000] interlock 1.1.0-dev (0b98d62)
DEBU[0000] using tls for communication with docker
DEBU[0000] docker client: url=tcp://192.168.99.101:3376
DEBU[0000] loading extension: name=nginx
INFO[0000] interlock node: id=0ec19fc84df5f127044efaca2c3b195276bb99711a5c583900589f89d38ab565  ext=lb
DEBU[0000] starting event handling
DEBU[0000] event received: status=interlock-start id=0 type= action=
DEBU[0000] notifying extension: lb
DEBU[0000] triggering reload                             ext=lb
DEBU[0001] reaping key: reload
DEBU[0001] triggering reload from cache                  ext=lb
DEBU[0001] checking to reload                            ext=lb
DEBU[0001] updating load balancers                       ext=lb
DEBU[0001] generating proxy config                       ext=lb
DEBU[0001] proxy config path: /etc/nginx/nginx.conf      ext=lb
DEBU[0001] saving proxy config                           ext=lb
FATA[0001] open /etc/interlock/nginx.conf.template: no such file or directory  ext=nginx

real	0m1.075s
user	0m0.020s
sys	0m0.050s
```

Is that fast enough or should I add a check early on in `run.go`?

I'll also put a couple of log messages in there before the FATAL on how to remediate the problem.

```
log().Infof("Missing nginx configuration template: template=%s", p.cfg.TemplatePath)
log().Infof("Examples of an nginx configuration template: url=https://github.com/ehazlett/interlock/tree/master/docs/examples/nginx")
```

**Comment by ehazlett** [comment]
ya that should be good

**Comment by everett-toews** [comment]
This is ready for final review. FWIW, tests are passing locally.

**Comment by everett-toews** [comment]
FWIW, I've got an image out there for testing this `etoews/interlock:templates` and here are some [example files](https://gist.github.com/everett-toews/df0b70686e686f1f4cf5) for working with it.

**Comment by everett-toews** [comment]
Ignore the "Experimental multi-interlock config" commits. When #110 merges, I'll rebase the externalized templates commits onto master and PR directly to master. The multi-interlock config will be another PR.

**Comment by ehazlett** [comment]
Thanks!  I'll get some time to check this out.

**Comment by everett-toews** [comment]
@ehazlett I'm going to squash and rebase this on master and give you a clean look at it.

**Comment by everett-toews** [comment]
Superseded by https://github.com/ehazlett/interlock/pull/113

**Pull request closed without merging**
