### PR TITLE
HAProxy: Use the primary domain config for all alias domains

### PR DESCRIPTION
**Pull request by tmrudick**
Previously, alias domains would not get the interlock config for the primary domain. For example, if ssl_only=true, only the primary domain would get this setting. All alias domains would have the default setting of ssl_only=false. Similarly, due to this, the load balancing algorithm for alias domains was always empty within the haproxy config.

Keep track of the primary domain when processing alias domains so that the interlock configurations are applied to all alias domains.

### CODE REVIEW

**Comment by ehazlett** [comment]
Hey thanks!  Would you mind checking out the `ng` branch?  I'm getting ready to merge that and I don't want to smash this commit.  Sorry and thanks!

**Comment by tmrudick** [comment]
Just getting back to this. Apologies for the delay. Just rebased on top of master so should be good to go.

**Comment by ehazlett** [comment]
I'm terribly sorry for missing this.  Would you mind rebasing and I will review as soon as it's done.  Thanks and apologies!!

**Comment by tmrudick** [comment]
No problem! Rebased against master. Please take another look.

**Comment by tmrudick** [comment]
Ping!

**Pull request closed without merging**
